// import { useEffect } from "react";
import ReactDom from "react-dom"
import Head from 'next/head'
import FloatingNav from '../components/FloatingNav'
import Agenda from '../sections/Agenda'
import GetStarted from '../sections/GetStarted'
import Hero from '../sections/Hero'
import Jobs from '../sections/Jobs'
import styles from '../styles/Home.module.css'
import { useLocomotiveScroll } from 'react-locomotive-scroll';


export default function Home() {
  const { scroll } = useLocomotiveScroll();
  // const scrollRef = createRef()

  // useEffect(() => {
  //   const scroll = new LocomotiveScroll({
  //     el: scrollRef.current,
  //     smooth: true
  //   });
  // })

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;400;600;700&display=swap" rel="stylesheet" />
      </Head>
      {/* <main data-scroll-section className="relative"> */}
        <Hero />
        <GetStarted />
        <Agenda />
        <Jobs />
        <FloatingNav />
      {/* </main> */}
    </div>
  )
}
